ideas/urls.py
from django.urls import path

#from . import views
from .views import IdeaListView, IdeaDetailView, about



urlpatterns = [
    path('', IdeaListView.as_view(), name = 'ideas-home'),
    path('ideas/<int:pk>/', IdeaDetailView.as_view(), name = 'idea-detail'),
    path('about/', about, name = 'ideas-about')
]

manzana/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from users.views import register, profile



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register, name = 'register'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user = True, template_name = 'users/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name = 'users/password-reset.html'), name = 'password-reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name = 'users/password-reset-done.html'), name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'users/password-reset-confirm.html'), name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'users/password-reset-complete.html'), name = 'password_reset_complete'),
    path('profile/', profile, name = 'profile'),
    path('', include('ideas.urls')),
    path('tags/', include('tags.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tags/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.tags, name = 'ideas-tags')
]

ideas/models.py
from django.db import models
from django.utils import timezone
from users.models import Contributor
from tags.models import Tag



class Idea(models.Model):
	""" Store information on project ideas and plans"""

	contributors = models.ManyToManyField(Contributor)
	tags = models.ManyToManyField(Tag)
	name = models.CharField(max_length = 300)
	draft = models.TextField(blank = False, default = 'none')
	description = models.TextField(blank = False, default = 'none')
	date_created = models.DateTimeField(default = timezone.now)

	def __str__(self):
		return self.name 


class Task(models.Model):
	""" Store information about tasks for implementing a project idea (Idea)"""

	idea = models.ForeignKey(Idea, on_delete = models.CASCADE)
	name = models.TextField()

	def __str__(self):
		return self.name

ideas/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Idea, Task



#@login_required

"""
def home(request):

    data = {
        'ideas': Idea.objects.all(),
        'tasks': Task.objects.all()
    }
    return render(request, 'ideas/home.html', data)
"""

class IdeaListView(ListView):
    """list/read the Idea instances"""

    model = Idea  
    template_name = 'ideas/home.html'
    context_object_name = 'ideas'
    ordering = ['-date_created']

class IdeaDetailView(DetailView):
    """list/read a single Idea instance"""

    model = Idea 
    




def about(request):
    return render(request, 'ideas/about.html', {'title': 'about'})









""" Concrete View Classes
# CreateAPIView
Used for create-only endpoints.
# ListAPIView
Used for read-only endpoints to represent a collection of model instances.
# RetrieveAPIView
Used for read-only endpoints to represent a single model instance.
# DestroyAPIView
Used for delete-only endpoints for a single model instance.
# UpdateAPIView
Used for update-only endpoints for a single model instance.
# ListCreateAPIView
Used for read-write endpoints to represent a collection of model instances.
RetrieveUpdateAPIView
Used for read or update endpoints to represent a single model instance.
# RetrieveDestroyAPIView
Used for read or delete endpoints to represent a single model instance.
# RetrieveUpdateDestroyAPIView
Used for read-write-delete endpoints to represent a single model instance.
"""

ideas/templates/ideas/about.html
{% extends 'ideas/base.html' %}

{% block content %}

    <main class = "container">
        <div class = "row text-center justify-content-center">
            <div class = "col">
                <h1 class = "display-4"> About Manzana (temporary name)! </h1>
            </div>
        </div>
    </main>

{% endblock %}

ideas/templates/ideas/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset = "utf-8">
    <meta name = "viewport" content = "width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Bootstrap icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet"> 

    <!-- CSS -->
    <link rel = "stylesheet" type = "text/css" href = "{% static 'ideas/style.css' %}">
    
	{% if title %}
		<title> Manzana | {{ title }} </title>
	{% else %}
		<title> Manzana </title>
	{% endif %}
	<title> Manzana </title>
    
</head>
<body>

    {% if user.is_authenticated %}

        <header>

            <nav class = "navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
                <div class = "container">
                    <a href = "{% url 'ideas-home' %}" class = "navbar-brand"> Knowt </a>
                    <button
                    class = "navbar-toggler"
                    type = "button"
                    data-bs-toggle = "collapse"
                    data-bs-target = "#navmenu"
                    >
                    <span class = "navbar-toggler-icon"></span>
                    </button>

                    <div class = "collapse navbar-collapse" id = "navmenu">
                        <ul class = "navbar-nav ms-auto">
                            <li class = "nav-item me-3">
                                <a href = "{% url 'profile' %}" class = "nav-link"> Profile </a>
                            </li>
                            <a href = "{% url 'logout' %}"> 
                                <button class = "btn btn-outline-light"> Logout </button>
                            </a>
                        </ul>
                    </div>
                </div>
            </nav>

        </header>

    {% else %}

        <header>

            <nav class = "navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
                <div class = "container">
                    <a href = "{% url 'ideas-home' %}" class = "navbar-brand"> Knowt </a>
                    <button
                    class = "navbar-toggler"
                    type = "button"
                    data-bs-toggle = "collapse"
                    data-bs-target = "#navmenu"
                    >
                    <span class = "navbar-toggler-icon"></span>
                    </button>

                    <div class = "collapse navbar-collapse" id = "navmenu">
                        <ul class = "navbar-nav ms-auto">
                            <li class = "nav-item me-3">
                                <a href = "{% url 'ideas-about' %}" class = "nav-link"> About </a>
                            </li>
                            <a href = "{% url 'login' %}"> 
                                <button class = "btn btn-outline-light"> Log in </button>
                            </a>
                        </ul>
                    </div>
                </div>
            </nav>

        </header>

    {% endif %}

    <main>

        {% block content %}

        {% endblock %}
        
    </main>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ideas/templates/ideas/home.html
{% extends 'ideas/base.html' %}


{% block content %}

    {% if user.is_authenticated %}

        <div class = "container">

            <div class = "row">
                
                <div class = "col-md-2">
                    <div class = "content-section">
                        <ul class = "list-group">
                            <a class = "list-group-item list-group-item-light" href = "#">
                                <span><i class = "bi bi-lightbulb-fill"></i></span>
                                <span> My ideas </span>
                            </a>
                            <a class = "list-group-item list-group-item-light" href = "#">
                                <span><i class = "bi bi-bookmark-fill"></i></span>
                                <span> Saved ideas </span>
                            </a>
                            <a class = "list-group-item list-group-item-light" href = "#">
                                <span><i class = "bi bi-tag-fill"></i></span>
                                <span> Tags </span>
                            </a>
                            <a class = "list-group-item list-group-item-light" href = "#">
                                <span><i class = "bi bi-people-fill"></i></span>
                                <span> Contributors </span>
                            </a>
                        </ul>
                    </div>
                </div>  

                <div class = "col-md-8">
                    {% for idea in ideas %}
                        <article class = "card mb-3">
                            <div class = "card-body">
                                <div class = "row">
                                    <div class = "col-md-10">
                                        <a href = "{% url 'idea-detail' idea.id %}" class = "card-title">
                                            <h4 class = "text-dark"> {{ idea.name }} </h4>
                                        </a>
                                        <p class = "card-text text-break"> 
                                            {{ idea.description|slice:":250" }} ...
                                        </p>
                                        <span class="badge bg-secondary">
                                            <a class = "text-light" href = "#"> tag1 </a>
                                        </span>
                                        <span class="badge bg-secondary">
                                            <a class = "text-light" href = "#"> tag2 </a>
                                        </span>
                                        <div class = "d-inline float-end">
                                            {% for contributor in idea.contributors.all %}
                                                <small> Created by {{ contributor }} </small>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class = "col-md-2 text-muted text-end">
                                        <small class = "mb-3"> 
                                            {{ idea.date_created|date:"F d, Y" }} 
                                        </small>
                                        <small class = "mb-2"> 0 views </small>
                                        <small> 0 tasks </small>
                                    </div>
                                </div>
                            </div>                  
                        </article>
                    {% endfor %}
                </div>

                <div class = "col-md-2">
                    <div class = "content-section">
                        <ul class = "list-group">
                            <a class = "list-group-item list-group-item-light" href = "#">
                                <span><i class = "bi bi-lightbulb-fill"></i></span>
                                <span> My ideas </span>
                            </a>
                            <a class = "list-group-item list-group-item-light" href = "#">
                                <span><i class = "bi bi-bookmark-fill"></i></span>
                                <span> Saved ideas </span>
                            </a>
                            <a class = "list-group-item list-group-item-light" href = "#">
                                <span><i class = "bi bi-tag-fill"></i></span>
                                <span> Tags </span>
                            </a>
                            <a class = "list-group-item list-group-item-light" href = "#">
                                <span><i class = "bi bi-people-fill"></i></span>
                                <span> Contributors </span>
                            </a>
                        </ul>
                    </div>
                </div>  

            </div>

            <!--
            {% for idea in ideas %}
                <div>
                    <div>
                        <a class = "mr-2" href = "#"> {{ idea.author }} </a>
                        {% for contributor in idea.contributors.all %}
                            <small> {{ contributor }} </small>
                        {% endfor %}
                        <small> {{ idea.date_created }} </small>
                    </div>
                    <div>
                        <h2><a href = "#"> {{ idea.name }} </a></h2>
                        <p> {{ idea.description }} </p>
                        {% for task in idea.task_set.all %}
                            <ul>
                                <li> {{ task.name }} </li>
                            </ul>
                        {% endfor %}
                        {% for tag in idea.tags.all %}
                            <small> {{ tag }} </small>
                        {% endfor %}
                    </div>
                </div>
                <br/>
            {% endfor %}
            -->

        </div>

    {% else %}

        <div class = "container">
            
            <div class = "section text-dark text-center">
                <h1> Plan Your Prosocial AI Project </h1>
                <p>
                    Create and contribute project ideas with intelligent<br/>
                    plans to save the world
                </p>
                <a href = "{% url 'register' %}">
                    <button class = "btn btn-outline-dark mt-2"> Join </button>
                </a>
            </div>

        </div>

    {% endif %}
 

{% endblock %}

ideas/templates/ideas/idea_detail.html
{% extends 'ideas/base.html' %}


{% block content %}

    <div class = "container">

        <div class = "row">
            
            <div class = "col-md-2">
                <div class = "content-section">
                    <ul class = "list-group">
                        <a class = "list-group-item list-group-item-light" href = "#">
                            <span><i class = "bi bi-lightbulb-fill"></i></span>
                            <span> My ideas </span>
                        </a>
                        <a class = "list-group-item list-group-item-light" href = "#">
                            <span><i class = "bi bi-bookmark-fill"></i></span>
                            <span> Saved ideas </span>
                        </a>
                        <a class = "list-group-item list-group-item-light" href = "#">
                            <span><i class = "bi bi-tag-fill"></i></span>
                            <span> Tags </span>
                        </a>
                        <a class = "list-group-item list-group-item-light" href = "#">
                            <span><i class = "bi bi-people-fill"></i></span>
                            <span> Contributors </span>
                        </a>
                    </ul>
                </div>
            </div>  

            <div class = "col-md-8">
                <article class = "card mb-3">
                    <div class = "card-body">
                        <div class = "mb-3">
                            <!--
                            {% for tag in object.tags.all %}
                                <span class = "badge bg-secondary me-2">
                                    <a class = "text-light" href = "#"> {{ tag }} </a>
                                </span>
                            {% endfor %}
                            -->
                            <span class = "badge bg-secondary me-2">
                                <a class = "text-light" href = "#"> tag1 </a>
                            </span>
                            <span class = "badge bg-secondary">
                                <a class = "text-light" href = "#"> tag2 </a>
                            </span>
                            <span class = "float-end"><i class = "bi bi-gear"></i></span>
                        </div>
                        <div class = "mb-4">
                            <h3 class = "text-dark"> {{ object.name }} </h3>
                            <small class = "text-muted">
                                {{ object.date_created|date:"F d, Y" }}
                            </small>
                        </div>
                        <div class = "mb-4">
                            <h5> Description </h5>
                            <p class = "card-text text-break"> 
                                {{ object.description }}
                            </p>
                        </div>
                        <div class = "mb-4">
                            <h5 class = "mb-4"> Tasks </h5>
                            {% for task in object.task_set.all %}
                                <div class = "card mt-2">
                                    <small> {{ task.name }} </small>
                                </div>                           
                            {% endfor %}
                        </div>
                        <div>
                            <h5 class = "mb-4"> Contributors </h5>
                            <div class = "grid-container">
                                {% for contributor in object.contributors.all %}
                                    <div class = "card w-25 h-25">
                                        <div class = "d-flex flex-row gap-3">
                                            <div>
                                                <img class = "rounded-circle article-img" src = "{{ contributor.profile.picture.url }}">
                                            </div>
                                            <div class = "text-break">
                                                <a style = "font-size: 13px;" href = "#"> 
                                                    {{ contributor }}
                                                </a>
                                                <small style = "font-size: 13px;" class = "d-block"> N° ideas </small>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <!--
                            <h5 class = "mb-4"> Contributors </h5>
                            {% for contributor in object.contributors.all %}
                                <article class = "w-25 h-25">
                                    <div class = "d-inline">
                                        <img class="rounded-circle article-img" src="{{ contributor.profile.picture.url }}">
                                    </div>
                                    <div class = "d-inline">
                                        <a href = "#">{{ contributor }}</a>
                                        <small class = "d-block"> N° ideas </small>
                                    </div>
                                </article>
                            {% endfor %}
                            -->
                        </div>
                    </div>                  
                </article>
            </div>

            <div class = "col-md-2">
                <div class = "content-section">
                    <ul class = "list-group">
                        <a class = "list-group-item list-group-item-light" href = "#">
                            <span><i class = "bi bi-lightbulb-fill"></i></span>
                            <span> My ideas </span>
                        </a>
                        <a class = "list-group-item list-group-item-light" href = "#">
                            <span><i class = "bi bi-bookmark-fill"></i></span>
                            <span> Saved ideas </span>
                        </a>
                        <a class = "list-group-item list-group-item-light" href = "#">
                            <span><i class = "bi bi-tag-fill"></i></span>
                            <span> Tags </span>
                        </a>
                        <a class = "list-group-item list-group-item-light" href = "#">
                            <span><i class = "bi bi-people-fill"></i></span>
                            <span> Contributors </span>
                        </a>
                    </ul>
                </div>
            </div>  

        </div>

        <!--
        {% for idea in ideas %}
            <div>
                <div>
                    <a class = "mr-2" href = "#"> {{ idea.author }} </a>
                    {% for contributor in idea.contributors.all %}
                        <small> {{ contributor }} </small>
                    {% endfor %}
                    <small> {{ idea.date_created }} </small>
                </div>
                <div>
                    <h2><a href = "#"> {{ idea.name }} </a></h2>
                    <p> {{ idea.description }} </p>
                    {% for task in idea.task_set.all %}
                        <ul>
                            <li> {{ task.name }} </li>
                        </ul>
                    {% endfor %}
                    {% for tag in idea.tags.all %}
                        <small> {{ tag }} </small>
                    {% endfor %}
                </div>
            </div>
            <br/>
        {% endfor %}
        -->

    </div>

{% endblock %}